### ISSUE TITLE
KeyError: 'annotations'

### ISSUE THREAD

**Issue by JMcarrot** [epic-kitchens/C10-epic-sounds-detection#1]
Hi!
Thank you for releasing the baseline code!  When I run the eval command,
python eval.py configs/epic_sounds_auditory_slowfast.yaml <path_to_checkpoint>

I met KeyError: 'annotations', it seems the file baseline/data/epic_sounds/annotations/epic_sounds.json lacks annotations, how to get the  entire file or something else to modify?

By the way, how can I acquire the example json actionformer_baseline_validation.json?

**Comment by JacobChalk** [comment]
Hi,

Thank you for pointing out this error. This was due to the videos in the test set not containing a key for the annotations as they are not released. To fix this, we added an empty list as the 'annotations' for test set videos. Please pull the updates for the code to work.

We have also uploaded the ActionFormer baseline validation results under the "EvaluationCode" folder.
